

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
('1040107','Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', 4.56)

INSERT INTO [TABELA DE VENDEDORES]
([MAtRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00233','João Geraldo da Fonseca',0.10)