// <auto-generated />
namespace _02_Desenvolvedor_ASP_NET_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MaisLimitacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaisLimitacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201903052126315_MaisLimitacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
